<?php

namespace BelastingBundle\Repository;

/**
 * BelastingplichtigeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BelastingplichtigeRepository extends \Doctrine\ORM\EntityRepository
{
}
