<?php

namespace BelastingBundle\Repository;

/**
 * HuishoudenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HuishoudenRepository extends \Doctrine\ORM\EntityRepository
{
}
