<?php

namespace BelastingBundle\Repository;

/**
 * KinderopvangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KinderopvangRepository extends \Doctrine\ORM\EntityRepository
{
}
