<?php

namespace BelastingBundle\Repository;

/**
 * KindRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KindRepository extends \Doctrine\ORM\EntityRepository
{
}
