<?php

namespace BelastingBundle\Repository;

/**
 * WoningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WoningRepository extends \Doctrine\ORM\EntityRepository
{
}
